import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextResponse } from "next/server";
import { requirePermission } from "@/lib/auth";
import { db } from "@/lib/db";
export async function GET(request: Request) { await requirePermission("reports.sales"); const params = new URL(request.url).searchParams; const format = params.get("format") ?? "xlsx"; const from = params.get("from") ? new Date(params.get("from")!) : new Date(new Date().getFullYear(), new Date().getMonth(), 1); const to = params.get("to") ? new Date(params.get("to")!) : new Date(); const sales = await db.sale.findMany({ where: { createdAt: { gte: from, lte: to }, status: { not: "CANCELLED" } }, include: { customer: true, user: true }, orderBy: { createdAt: "asc" }, take: 10000 });
  if (format === "csv" || format === "xlsx") { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("VENTAS"); sheet.columns = [{ header: "Código", key: "code" }, { header: "Fecha", key: "date" }, { header: "Cliente", key: "customer" }, { header: "Cajero", key: "user" }, { header: "Total", key: "total" }, { header: "Estado", key: "status" }]; sales.forEach(s => sheet.addRow({ code: s.code, date: s.createdAt.toISOString(), customer: s.customer.legalName ?? `${s.customer.firstName ?? ""} ${s.customer.lastName ?? ""}`, user: s.user.name, total: s.total.toString(), status: s.status })); const data = format === "csv" ? await workbook.csv.writeBuffer() : await workbook.xlsx.writeBuffer(); return new NextResponse(Buffer.from(data), { headers: { "content-type": format === "csv" ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": `attachment; filename=reporte-ventas.${format}` } }); }
  if (format === "pdf") { const pdf = await PDFDocument.create(); const page = pdf.addPage([595, 842]); const font = await pdf.embedFont(StandardFonts.Helvetica); page.drawText("Reporte de ventas - Minimarket Don Lucho", { x: 40, y: 800, size: 15, font, color: rgb(0.1,0.3,0.2) }); let y = 775; for (const sale of sales.slice(0, 45)) { page.drawText(`${sale.code}  ${sale.createdAt.toLocaleDateString("es-PE")}  S/ ${sale.total.toString()}`, { x: 40, y, size: 9, font }); y -= 16; } const data = await pdf.save(); return new NextResponse(Buffer.from(data), { headers: { "content-type": "application/pdf", "content-disposition": "attachment; filename=reporte-ventas.pdf" } }); }
  return NextResponse.json({ success: false, message: "Formato inválido." }, { status: 400 });
}
