import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { AppError } from "@/lib/errors";
import { nextSequence } from "@/lib/sequence";
import { saleSchema } from "./schemas";

export async function createSale(raw: unknown, userId: string) {
  const input = saleSchema.parse(raw);
  return db.$transaction(async tx => {
    const repeated = await tx.sale.findUnique({ where: { idempotencyKey: input.idempotencyKey } }); if (repeated) return repeated;
    const cashSession = await tx.cashSession.findFirst({ where: { userId, status: "OPEN" } }); if (!cashSession) throw new AppError("CASH_NOT_OPEN", "Debes abrir caja antes de vender.", 409);
    const customer = await tx.customer.findUnique({ where: { id: input.customerId }, include: { credit: true } }); if (!customer || !customer.active) throw new AppError("CUSTOMER_NOT_FOUND", "Cliente no disponible.", 404);
    const products = await tx.product.findMany({ where: { id: { in: input.items.map(i => i.productId) }, active: true, deletedAt: null } }); if (products.length !== new Set(input.items.map(i => i.productId)).size) throw new AppError("PRODUCT_NOT_FOUND", "Uno o más productos no están disponibles.", 404);
    let subtotal = new Prisma.Decimal(0); const itemData = input.items.map(item => { const product = products.find(p => p.id === item.productId)!; const quantity = new Prisma.Decimal(item.quantity); if (!product.allowsDecimals && !quantity.isInteger()) throw new AppError("DECIMALS_NOT_ALLOWED", `${product.name} no admite cantidades decimales.`); if (!product.allowsNegativeStock && product.stock.lessThan(quantity)) throw new AppError("INSUFFICIENT_STOCK", `Stock insuficiente para ${product.name}.`, 409); const lineSubtotal = new Prisma.Decimal(item.unitPrice).mul(quantity).minus(item.discount); subtotal = subtotal.plus(lineSubtotal); return { product, quantity, unitPrice: new Prisma.Decimal(item.unitPrice), discount: new Prisma.Decimal(item.discount), subtotal: lineSubtotal }; });
    const total = subtotal.minus(input.discount); const paid = input.payments.filter(p => p.method !== "CREDIT").reduce((sum,p) => sum.plus(p.amount), new Prisma.Decimal(0)); const creditAmount = input.payments.filter(p => p.method === "CREDIT").reduce((sum,p) => sum.plus(p.amount), new Prisma.Decimal(0)); if (!paid.plus(creditAmount).equals(total)) throw new AppError("PAYMENT_MISMATCH", "La suma de pagos no coincide con el total."); if (creditAmount.greaterThan(0) && customer.general) throw new AppError("GENERAL_CUSTOMER_CREDIT", "No se puede fiar a Cliente General."); const currentDebt = customer.credit?.balance ?? new Prisma.Decimal(0); if (creditAmount.greaterThan(0) && currentDebt.plus(creditAmount).greaterThan(customer.creditLimit)) throw new AppError("CREDIT_LIMIT_EXCEEDED", "La operación excede el límite de crédito.", 409);
    const settings = await tx.businessSettings.findUnique({ where: { id: "singleton" } }); const code = await nextSequence(tx, "sale", settings?.salePrefix ?? "V");
    const sale = await tx.sale.create({ data: { code, customerId: customer.id, userId, cashSessionId: cashSession.id, subtotal, discount: input.discount, total, paidAmount: paid, creditAmount, idempotencyKey: input.idempotencyKey, status: creditAmount.greaterThan(0) ? "CREDIT_PENDING" : "COMPLETED", items: { create: itemData.map(i => ({ productId: i.product.id, quantity: i.quantity, unitPrice: i.unitPrice, unitCost: i.product.averageCost, discount: i.discount, subtotal: i.subtotal })) }, payments: { create: input.payments.map(p => ({ method: p.method, amount: p.amount, receivedAmount: p.receivedAmount, changeAmount: p.method === "CASH" && p.receivedAmount ? new Prisma.Decimal(p.receivedAmount).minus(p.amount) : undefined, reference: p.reference, operationCode: p.operationCode })) } } });
    for (const item of itemData) { const updated = await tx.product.update({ where: { id: item.product.id }, data: { stock: { decrement: item.quantity } } }); await tx.inventoryMovement.create({ data: { productId: item.product.id, previousStock: item.product.stock, quantity: item.quantity.negated(), resultingStock: updated.stock, unitCost: item.product.averageCost, type: "SALE", referenceType: "SALE", referenceId: sale.id, userId } }); }
    for (const payment of input.payments.filter(p => p.method !== "CREDIT")) await tx.cashMovement.create({ data: { cashSessionId: cashSession.id, type: "SALE", amount: payment.amount, paymentMethod: payment.method, referenceType: "SALE", referenceId: sale.id, description: code, userId } });
    if (creditAmount.greaterThan(0)) { const credit = await tx.customerCredit.upsert({ where: { customerId: customer.id }, create: { customerId: customer.id, balance: creditAmount }, update: { balance: { increment: creditAmount } } }); await tx.creditMovement.create({ data: { creditId: credit.id, type: "CHARGE", amount: creditAmount, balanceAfter: credit.balance, referenceType: "SALE", referenceId: sale.id, userId } }); }
    await audit({ userId, action: "CREATE", module: "sales", resource: "Sale", resourceId: sale.id, after: { code, total: total.toString(), paid: paid.toString(), credit: creditAmount.toString() } }, tx); return sale;
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, maxWait: 5000, timeout: 15000 });
}
