"use client";
import { useState } from "react";
import { FileSpreadsheet, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "./ui/button";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "./ui/select";
import { Table,TableHeader,TableRow,TableHead,TableBody,TableCell } from "./ui/table";
import { importConfig,type ImportEntity } from "@/modules/imports/config";

type Preview={type:ImportEntity;fileName:string;totalRows:number;headers:string[];mapping:Record<string,string|null>;rows:Record<string,string>[];required:string[];fields:{key:string;label:string}[]};
const types=Object.entries(importConfig) as [ImportEntity,(typeof importConfig)[ImportEntity]][];

export function ImportProducts(){
  const[type,setType]=useState<ImportEntity>("products");const[preview,setPreview]=useState<Preview|null>(null);const[file,setFile]=useState<File|null>(null);const[loading,setLoading]=useState(false);const[strategy,setStrategy]=useState("SKIP");
  async function upload(selected:File){setLoading(true);setFile(selected);try{const form=new FormData();form.set("file",selected);form.set("type",type);const response=await fetch("/api/imports/preview",{method:"POST",body:form}),json=await response.json();if(!response.ok)throw new Error(json.message);setPreview(json.data)}catch(e){setFile(null);toast.error(e instanceof Error?e.message:"No se pudo leer el archivo")}finally{setLoading(false)}}
  async function confirm(){if(!file||!preview)return;setLoading(true);try{const form=new FormData();form.set("file",file);form.set("type",type);form.set("mapping",JSON.stringify(preview.mapping));form.set("strategy",strategy);const response=await fetch("/api/imports/confirm",{method:"POST",body:form}),json=await response.json();if(!response.ok)throw new Error(json.message);toast.success(`Importación terminada: ${json.data.created} creados, ${json.data.updated} actualizados, ${json.data.skipped} omitidos, ${json.data.errors} errores`);setPreview(null);setFile(null)}catch(e){toast.error(e instanceof Error?e.message:"No se pudo importar")}finally{setLoading(false)}}
  const config=importConfig[type];const valid=!preview||preview.required.every(field=>Object.values(preview.mapping).includes(field));
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{types.map(([key,item])=><button type="button" key={key} onClick={()=>{if(!preview){setType(key);setFile(null)}}} className={`min-w-52 rounded-2xl p-4 text-left shadow-sm transition ${type===key?"bg-primary text-primary-foreground":"bg-card hover:bg-muted/50"}`}><FileSpreadsheet className="size-5"/><p className="mt-3 text-sm font-semibold">{item.label}</p><p className={`mt-1 text-xs leading-5 ${type===key?"text-primary-foreground/75":"text-muted-foreground"}`}>{item.description}</p></button>)}</div>
    <div className="flex flex-col gap-3 rounded-2xl bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Importar {config.label.toLowerCase()}</p><p className="text-xs text-muted-foreground">Admite XLSX y CSV · máximo 5000 filas.</p></div><Button asChild variant="secondary"><a href={`/api/imports/template?type=${type}`}>Descargar plantilla</a></Button></div>
    {!preview?<label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const selected=e.dataTransfer.files[0];if(selected)void upload(selected)}} className="flex min-h-60 cursor-pointer flex-col items-center justify-center rounded-2xl bg-muted/30 p-6 text-center shadow-sm transition hover:bg-muted/45"><Upload className="size-10 text-primary"/><strong className="mt-4">Arrastra tu Excel o CSV aquí</strong><span className="my-2 text-sm text-muted-foreground">o selecciona un archivo</span><span className="rounded-xl bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm">{loading?"Leyendo…":"Seleccionar archivo"}</span><input type="file" accept=".xlsx,.csv" className="hidden" disabled={loading} onChange={e=>{const selected=e.target.files?.[0];if(selected)void upload(selected)}}/></label>:<>
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Mapeo de columnas · {config.label}</h2><p className="text-sm text-muted-foreground">{preview.fileName} · {preview.totalRows} filas</p></div><Button variant="secondary" onClick={()=>{setPreview(null);setFile(null)}}>Cambiar archivo</Button></div>
      <div className="grid gap-3 rounded-2xl bg-card p-4 shadow-sm md:grid-cols-2">{preview.headers.map(header=><label key={header} className="grid gap-2 text-sm sm:grid-cols-[minmax(0,1fr)_minmax(170px,1fr)] sm:items-center"><span className="truncate">{header}</span><select value={preview.mapping[header]??""} onChange={e=>setPreview({...preview,mapping:{...preview.mapping,[header]:e.target.value||null}})} className="h-10 min-w-0 rounded-xl bg-muted/40 px-3 text-sm shadow-sm outline-none focus:ring-2 focus:ring-ring/20"><option value="">No importar</option>{preview.fields.map(field=><option key={field.key} value={field.key}>{field.label}{preview.required.includes(field.key)?" *":""}</option>)}</select></label>)}</div>
      <div className="w-full overflow-x-auto rounded-2xl bg-card shadow-sm"><Table className="min-w-max"><TableHeader><TableRow>{preview.headers.map(h=><TableHead key={h} className="whitespace-nowrap">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{preview.rows.slice(0,10).map((row,i)=><TableRow key={i}>{preview.headers.map(h=><TableCell key={h} className="max-w-72 whitespace-nowrap">{row[h]}</TableCell>)}</TableRow>)}</TableBody></Table></div>
      <div className="flex flex-col gap-4 rounded-2xl bg-card p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between"><div className="space-y-2"><span className="text-sm font-medium">Registros existentes</span><Select value={strategy} onValueChange={setStrategy}><SelectTrigger className="w-full sm:w-64"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="SKIP">Omitir existentes</SelectItem><SelectItem value="UPDATE">Actualizar existentes</SelectItem></SelectContent></Select><p className="text-xs text-muted-foreground">{type==="sales"?"Las ventas se registran como operaciones nuevas; la estrategia no altera ventas existentes.":"La coincidencia usa DNI/RUC, SKU/código o RUC según el tipo."}</p></div><Button disabled={loading||!valid} onClick={confirm}>{loading?"Importando…":"Confirmar importación"}</Button></div>
      {!valid&&<p className="text-sm text-destructive">Mapea todos los campos obligatorios marcados con *.</p>}
    </>}
  </div>
}
