"use client";
import { useCallback,useEffect,useRef,useState } from "react";import { Camera,CameraOff,Loader2,ScanLine,TriangleAlert } from "lucide-react";import { Button } from "./ui/button";import { Alert,AlertDescription } from "./ui/alert";
type ScanResult={rawValue?:string;getText?:()=>string};type NativeDetector=new(o?:{formats?:string[]})=>{detect(v:HTMLVideoElement):Promise<ScanResult[]>};type Controls={stop():void};type ZXing={BrowserMultiFormatReader:new()=>{decodeFromConstraints(c:MediaStreamConstraints,v:HTMLVideoElement,cb:(r:ScanResult|undefined)=>void):Promise<Controls>}};declare global{interface Window{BarcodeDetector?:NativeDetector;ZXingBrowser?:ZXing}}
const SOURCES=["https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js","https://unpkg.com/@zxing/browser@0.1.5/umd/zxing-browser.min.js"];
async function loadZXing(){if(window.ZXingBrowser)return window.ZXingBrowser;for(const src of SOURCES){try{await new Promise<void>((resolve,reject)=>{const old=document.querySelector<HTMLScriptElement>(`script[src=\"${src}\"]`);if(old){if(window.ZXingBrowser)return resolve();old.addEventListener("load",()=>resolve(),{once:true});old.addEventListener("error",()=>reject(),{once:true});return}const s=document.createElement("script");s.src=src;s.async=true;s.crossOrigin="anonymous";s.onload=()=>resolve();s.onerror=()=>reject();document.head.appendChild(s)});if(window.ZXingBrowser)return window.ZXingBrowser}catch{}}throw new Error("No se pudo cargar el lector compatible con este navegador.")}
export function MobileCameraScanner({onScan}:{onScan:(code:string)=>void}){const videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),controlsRef=useRef<Controls|null>(null),rafRef=useRef(0),lastRef=useRef({code:"",at:0}),scanRef=useRef(onScan);const[active,setActive]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);useEffect(()=>{scanRef.current=onScan},[onScan]);
const emit=useCallback((code?:string)=>{const value=code?.trim();if(!value)return;const now=Date.now();if(value!==lastRef.current.code||now-lastRef.current.at>2500){lastRef.current={code:value,at:now};scanRef.current(value)}},[]);
const stop=useCallback(()=>{cancelAnimationFrame(rafRef.current);controlsRef.current?.stop();controlsRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setActive(false)},[]);
const startNative=useCallback(async(video:HTMLVideoElement,Detector:NativeDetector)=>{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;video.srcObject=stream;await video.play();const detector=new Detector({formats:["qr_code","ean_13","ean_8","code_128","code_39","upc_a","upc_e"]});const tick=async()=>{if(!streamRef.current||!videoRef.current)return;try{const r=await detector.detect(videoRef.current);emit(r[0]?.rawValue)}catch{}rafRef.current=requestAnimationFrame(()=>void tick())};void tick()},[emit]);
const startFallback=useCallback(async(video:HTMLVideoElement)=>{const ZX=await loadZXing(),reader=new ZX.BrowserMultiFormatReader();controlsRef.current=await reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false},video,r=>emit(r?.getText?.()))},[emit]);
const start=useCallback(async()=>{setError(null);if(!window.isSecureContext&&location.hostname!=="localhost")return setError("La cámara requiere HTTPS. Abre la versión publicada en Vercel o un dominio seguro.");if(!navigator.mediaDevices?.getUserMedia)return setError("Este navegador no permite acceso a la cámara.");setLoading(true);setActive(true);try{await new Promise(r=>requestAnimationFrame(()=>r(null)));const video=videoRef.current;if(!video)throw new Error("No se pudo preparar la vista de cámara.");if(window.BarcodeDetector)await startNative(video,window.BarcodeDetector);else await startFallback(video)}catch(e){stop();if(e instanceof DOMException&&e.name==="NotAllowedError")setError("Permiso de cámara denegado. Habilita Cámara para este sitio.");else if(e instanceof DOMException&&e.name==="NotFoundError")setError("No se encontró una cámara disponible.");else if(e instanceof DOMException&&e.name==="NotReadableError")setError("La cámara está ocupada por otra aplicación.");else setError(e instanceof Error?e.message:"No se pudo abrir la cámara.")}finally{setLoading(false)}},[startFallback,startNative,stop]);useEffect(()=>stop,[stop]);
return <div className="space-y-3"><div className="rounded-xl bg-muted/40 p-3"><div className="flex items-center gap-2"><Camera className="size-4 text-muted-foreground"/><div><p className="text-sm font-medium">Cámara del celular</p><p className="text-xs text-muted-foreground">Alternativa al lector físico USB/Bluetooth.</p></div></div></div>{active&&<div className="relative overflow-hidden rounded-xl bg-black shadow-sm"><video ref={videoRef} playsInline muted autoPlay className="aspect-[4/3] w-full object-cover"/><div className="pointer-events-none absolute inset-[12%]"><span className="absolute left-0 top-0 size-8 border-l-2 border-t-2 border-white"/><span className="absolute right-0 top-0 size-8 border-r-2 border-t-2 border-white"/><span className="absolute bottom-0 left-0 size-8 border-b-2 border-l-2 border-white"/><span className="absolute bottom-0 right-0 size-8 border-b-2 border-r-2 border-white"/><div className="absolute left-[8%] right-[8%] top-1/2 h-px bg-white/90"/></div><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-full bg-black/60 px-3 py-1.5 text-xs text-white backdrop-blur"><ScanLine className="size-3.5"/>Apunta al QR o código</div></div>}{error&&<Alert className="border-0 bg-amber-500/10 text-amber-700 dark:text-amber-400"><TriangleAlert className="size-4"/><AlertDescription>{error}</AlertDescription></Alert>}{!active?<Button type="button" variant="secondary" className="w-full" disabled={loading} onClick={()=>void start()}>{loading?<Loader2 className="size-4 animate-spin"/>:<Camera className="size-4"/>}{loading?"Abriendo cámara...":"Escanear con cámara"}</Button>:<Button type="button" variant="secondary" className="w-full" onClick={stop}><CameraOff className="size-4"/>Cerrar cámara</Button>}</div>}
