export const importTypes = ["products","customers","suppliers","inventory","sales"] as const;
export type ImportEntity = typeof importTypes[number];
export type ImportField = string;
export const importConfig: Record<ImportEntity,{label:string;description:string;required:string[];fields:{key:string;label:string;aliases:string[]}[]}>={
products:{label:"Productos",description:"Catálogo, precios, stock y códigos.",required:["name","unit","salePrice"],fields:[
{key:"sku",label:"SKU",aliases:["sku","codigo","código"]},{key:"barcode",label:"Código de barras",aliases:["codigo barras","código barras","barcode","ean","upc"]},{key:"name",label:"Nombre",aliases:["producto","nombre","nombre producto"]},{key:"description",label:"Descripción",aliases:["descripcion","descripción","detalle"]},{key:"category",label:"Categoría",aliases:["categoria","categoría","rubro"]},{key:"brand",label:"Marca",aliases:["marca","fabricante"]},{key:"unit",label:"Unidad",aliases:["unidad","unidad medida","um"]},{key:"purchasePrice",label:"Precio compra",aliases:["precio compra","costo"]},{key:"salePrice",label:"Precio venta",aliases:["precio","precio venta","pvp"]},{key:"stock",label:"Stock",aliases:["stock","cantidad","existencia"]},{key:"minimumStock",label:"Stock mínimo",aliases:["stock minimo","stock mínimo"]}]},
customers:{label:"Clientes",description:"Personas o empresas con datos de contacto y crédito.",required:[],fields:[
{key:"firstName",label:"Nombres",aliases:["nombres","nombre","first name"]},{key:"lastName",label:"Apellidos",aliases:["apellidos","apellido"]},{key:"legalName",label:"Razón social",aliases:["razon social","razón social","empresa"]},{key:"dni",label:"DNI",aliases:["dni","documento"]},{key:"ruc",label:"RUC",aliases:["ruc"]},{key:"phone",label:"Teléfono",aliases:["telefono","teléfono","celular"]},{key:"email",label:"Correo",aliases:["email","correo"]},{key:"address",label:"Dirección",aliases:["direccion","dirección"]},{key:"creditLimit",label:"Límite crédito",aliases:["limite credito","límite crédito","credito"]}]},
suppliers:{label:"Proveedores",description:"Proveedores y datos de contacto.",required:["legalName"],fields:[
{key:"legalName",label:"Razón social",aliases:["razon social","razón social","proveedor","nombre"]},{key:"tradeName",label:"Nombre comercial",aliases:["nombre comercial","trade name"]},{key:"ruc",label:"RUC",aliases:["ruc"]},{key:"contactName",label:"Contacto",aliases:["contacto","persona contacto"]},{key:"phone",label:"Teléfono",aliases:["telefono","teléfono","celular"]},{key:"email",label:"Correo",aliases:["email","correo"]},{key:"address",label:"Dirección",aliases:["direccion","dirección"]}]},
inventory:{label:"Inventario",description:"Ajustes masivos de existencias por SKU o código.",required:["sku","stock"],fields:[
{key:"sku",label:"SKU",aliases:["sku","codigo","código"]},{key:"stock",label:"Stock objetivo",aliases:["stock","cantidad","existencia"]},{key:"reason",label:"Motivo",aliases:["motivo","razon","razón"]}]},
sales:{label:"Ventas",description:"Carga ventas desde Excel. Requiere caja abierta, clientes y productos existentes.",required:["customer","sku","quantity","unitPrice","paymentMethod"],fields:[
{key:"saleRef",label:"Referencia venta",aliases:["venta","referencia","ticket","codigo venta"]},{key:"customer",label:"Cliente (DNI/RUC)",aliases:["cliente","dni cliente","ruc cliente"]},{key:"sku",label:"SKU producto",aliases:["sku","producto","codigo producto"]},{key:"quantity",label:"Cantidad",aliases:["cantidad","qty"]},{key:"unitPrice",label:"Precio unitario",aliases:["precio","precio unitario"]},{key:"paymentMethod",label:"Método pago",aliases:["metodo pago","método pago","pago"]}]}
};
export function normalizeHeader(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ")}
export function suggestMapping(headers:string[],type:ImportEntity){const fields=importConfig[type].fields;return Object.fromEntries(headers.map(header=>{const normalized=normalizeHeader(header);const field=fields.find(f=>[f.key,...f.aliases].some(alias=>normalizeHeader(alias)===normalized));return[header,field?.key??null]}))}
export function parseDecimal(value:unknown){const clean=String(value??"").trim().replace(/^S\/\s*/i,"").replace(/\s/g,"");if(!clean)return null;const normalized=clean.includes(",")&&!clean.includes(".")?clean.replace(",","."):clean.replace(/,/g,"");if(!/^[-+]?\d+(\.\d+)?$/.test(normalized))return null;return normalized}
